name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # Or specify a pnpm version if needed
          run_install: false # We'll run install manually

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check Formatting
        run: pnpm run format --check

      # Modified step to run coverage
      - name: Run Unit Tests with Coverage
        run: pnpm run test:coverage

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run E2E Tests
        run: pnpm run test:e2e

      # New step to upload coverage to Coveralls
      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          # The repo token is automatically passed by the action in most cases
          # You might need to set COVERALLS_REPO_TOKEN secret in repo settings
          # if the action cannot automatically determine it.
          # repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }} # Usually not needed for public repos
          path-to-lcov: ./coverage/lcov.info # Path to the lcov file generated by Vitest
          flag-name: run-${{ matrix.os }} # Optional: Flag runs if using matrix strategy
          parallel: false # Set to true if running jobs in parallel

      - name: Build Project
        run: pnpm run build
